---
vscode_extensions:
  - 1yib.nodejs-bundle
  - 1yib.svelte-bundle
  - alefragnani.project-manager
  - ardenivanov.svelte-intellisense
  - automatalabs.copilot-mcp
  - bierner.emojisense
  - bierner.markdown-emoji
  - bierner.markdown-footnotes
  - bierner.markdown-mermaid
  - bpruitt-goddard.mermaid-markdown-syntax-highlighting
  - buildwithlayer.mcp-integration-expert-eligr
  - davidanson.vscode-markdownlint
  - eamodio.gitlens
  - editorconfig.editorconfig
  - esbenp.prettier-vscode
  - espressif.esp-idf-extension
  - fivethree.vscode-svelte-snippets
  - foam.foam-vscode
  - github.copilot-chat
  - github.remotehub
  - github.vscode-github-actions
  - github.vscode-pull-request-github
  - gruntfuggly.todo-tree
  - idanp.checkpatch
  - iliazeus.vscode-ansi
  - james-yu.latex-workshop
  - jebbs.markdown-extended
  - jock.svg
  - josetr.cmake-language-support-vscode
  - kingwampy.raspberrypi-sync
  - marp-team.marp-vscode
  - marus25.cortex-debug
  - mathematic.vscode-latex
  - mathematic.vscode-pdf
  - mcu-debug.debug-tracker-vscode
  - mcu-debug.memory-view
  - mcu-debug.peripheral-viewer
  - mcu-debug.rtos-views
  - mermaidchart.vscode-mermaid-chart
  - ms-azuretools.vscode-containers
  - ms-azuretools.vscode-docker
  - ms-ceintl.vscode-language-pack-de
  - ms-dotnettools.vscode-dotnet-runtime
  - ms-edgedevtools.vscode-edge-devtools
  - ms-python.debugpy
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-python.vscode-python-envs
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode-remote.remote-wsl
  - ms-vscode-remote.vscode-remote-extensionpack
  - ms-vscode.azure-repos
  - ms-vscode.cmake-tools
  - ms-vscode.cpptools
  - ms-vscode.cpptools-extension-pack
  - ms-vscode.cpptools-themes
  - ms-vscode.hexeditor
  - ms-vscode.remote-explorer
  - ms-vscode.remote-repositories
  - ms-vscode.remote-server
  - ms-vscode.vscode-serial-monitor
  - nordic-semiconductor.nrf-kconfig
  - paulober.pico-w-go
  - philipbe.theme-gray-matter
  - platformio.platformio-ide
  - pomdtr.excalidraw-editor
  - raspberry-pi.raspberry-pi-pico
  - rvest.vs-code-prettier-eslint
  - shd101wyy.markdown-preview-enhanced
  - standard.vscode-standard
  - svelte.svelte-vscode
  - trond-snekvik.devicetree
  - trond-snekvik.simple-rst
  - twxs.cmake
  - vadimcn.vscode-lldb
  - vsls-contrib.gitdoc
  - vstirbu.vscode-mermaid-preview
  - yatki.vscode-surround
  - ycsin.zephyrproject-extension-pack
  - yzhang.markdown-all-in-one
