---
- name: IT/Netzwerk-Pakete installieren
  apt:
    name:
      - wireshark
      - nmap
      - tcpdump
      - ethtool
      - iperf3
      - minicom
      - lxc
      - docker.io
      - docker-compose
      - bind9
      - isc-dhcp-server
      - apache2
      - nginx
      - postgresql
      - php
      - samba
      - openvpn
      - suricata
      - zabbix-agent
    state: present
  tags: it_pakete

- name: Docker-Benutzer hinzuf√ºgen
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  tags: docker_user

- name: Docker-Compose-Projektvorlage kopieren
  copy:
    src: docker/
    dest: /home/{{ ansible_user }}/docker_projekte/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: docker_projekt
